### ISSUE TITLE
On-demand SDDC creation support ETA

### ISSUE THREAD

**Issue by aws-rafams** [NetApp-Automation/DRO#1]
Hi all! 
Browsing through the documentation DRO currently supports an existing pilot-light cluster. Is there an ETA for on-demand cluster support?
Thanks in advance

**Comment by netapp-dhruv-tyagi** [comment]
Hi Rafael,

Thanks for reaching out. On-demand SDDC is on the roadmap. We will have the communication out as soon as it is available.

Stay tuned!
